VIRTUAL_WIDTH = 1280
VIRTUAL_HEIGHT = 720

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

BACKGROUND_SIZE = 256
BACKGROUND_SPEED = 50
BACKGROUNDS = {'bg_black', 'bg_blue', 'bg_dark-purple'}
MENU_BACKGROUND = 'bg_black'

PLAYER_LASER_SPEED = 500

METEOR_SPEED = 80
METEOR_SPAWN_INTERVAL = {1, 5}
METEOR_TYPES = {}       -- gets filled after load
METEOR_COLLISION_DAMAGE = 0.5

ENEMY_SPAWN_INTERVAL = {3, 7}
ENEMY_COLLOSION_DAMAGE = 1
SCREEN_BARRIER_SIZE = 170

POWERUP_SPEED = 60
POWERUP_PROB_MAX = 80
NO_POWERUP_THRESH = 9

FILE_HIGHSCORES = "highscores"
HIGHSCORES_LIMIT = 10

EXPLOSION_SHORT_COUNT = 17
EXPLOSION_MEDIUM_COUNT = 13

VERSION = getVersion()
DEBUG = false