VIRTUAL_WIDTH = 1600 
VIRTUAL_HEIGHT = 1000

WINDOW_WIDTH = 1600
WINDOW_HEIGHT = 1000

HUD_PADDING = 20
HUD_ITEM_MARGIN = 40

HEALTH_BAR_TEXT_OFFSET = 18

GAME_SPEED_MULTIPLIER = 1.2

BACKGROUND_SIZE = 256
BACKGROUND_SPEED = 50
BACKGROUNDS = {'bg_black', 'bg_blue', 'bg_dark-purple'}
MENU_BACKGROUND = 'bg_black'

NEBULA_COUNT = 4
NEBULA_HEIGHT = 2160
NEBULA_WIDTH = 2160
NEBULA_SPEED = 30

MENU_SELECTED_COLOR = {r = 150/255, g = 100/255, b = 255/255}

PLAYER_LASER_SPEED = 600 * GAME_SPEED_MULTIPLIER

METEOR_SPEED = 80
METEOR_TYPES = {}       -- gets filled after load
METEOR_COLLISION_DAMAGE = 0.5

ENEMY_COLLOSION_DAMAGE = 1
SCREEN_BARRIER_SIZE = 210

POWERUP_SPEED = 60
POWERUP_PROB_MAX = 80
NO_POWERUP_THRESH = 9

FILE_HIGHSCORES = "highscores"
HIGHSCORES_LIMIT = 10

EXPLOSION_SHORT_COUNT = 17
EXPLOSION_MEDIUM_COUNT = 13

-- get set in love.load() (main.lua)
EXPLOSION_BLAST_SHIP = nil   
EXPLOSION_BLAST_METEOR_SM = nil
EXPLOSION_BLAST_METEOR_MD = nil
EXPLOSION_BLAST_METEOR_LG = nil

VERSION = getVersion()
DEBUG = false