VIRTUAL_WIDTH = 1280
VIRTUAL_HEIGHT = 720

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

BACKGROUND_SIZE = 256
BACKGROUND_SPEED = 50
BACKGROUNDS = {'bg_black', 'bg_blue', 'bg_dark-purple'}

GAME_OBJECT_TYPES = {'meteors', 'lasers', 'particles', 'items'}

PLAYER_LASER_SPEED = 500

METEOR_SPEED = 80
METEOR_SPAWN_INTERVAL = {1, 5}
METEOR_TYPES = {}       -- gets filled after load
METEOR_COLLISION_DAMAGE = 0.5

ENEMY_SPAWN_INTERVAL = {3, 7}
ENEMY_COLLOSION_DAMAGE = 1

POWERUP_SPEED = 60

FILE_HIGHSCORES = "highscores"
HIGHSCORES_LIMIT = 10

EXPLOSION_SHORT_COUNT = 17
EXPLOSION_MEDIUM_COUNT = 13

DEBUG = false