name: Luacheck
on:
  push:
    branches:
      - '**'
jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Luacheck
        uses: nebularg/actions-luacheck@v1
