name: Luacheck
on:
  push:
    branches:
      - '**'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          files: main.lua src/*
          args: --std +love -g
